// DisplayXR inline-3D demo gallery.
//
// Five DisplayXR demos, each introduced by its **3D workspace logo woven inline**:
// glasses-free 3D on DisplayXR hardware, a flat 2D crop everywhere else. Clicking a
// tile opens the demo's GitHub repo.
//
// The logos are the demos' own fixed 2-view assets (1024x512 side-by-side L|R,
// generated by /make-app-logos and shipped in each repo's displayxr.json manifest).
// Painting a fixed SBS image into an inline-3d canvas is the proven per-element weave
// path (b4srv/b4_single.html) — no eye/rig consumption, so it exercises multi-element
// weave without the Kooima/scene-scale work the hello-cube sample is still refining.
//
// Geometry: each tile canvas is SQUARE on screen (one woven eye is square, 512x512).
// In the DisplayXR Browser the canvas buffer is the full 1024x512 SBS — the browser
// squishes it 2:1 into the square box and the weave interlaces L|R back to a correct
// square 3D logo. Elsewhere we paint only the LEFT half (a normal square 2D logo).

const DEMOS = [
  {
    key: 'mediaplayer',
    name: 'Media Player',
    blurb: 'Two-view video and image player for 3D displays.',
    repo: 'https://github.com/DisplayXR/displayxr-demo-mediaplayer',
  },
  {
    key: 'avatar',
    name: '3D Avatar',
    blurb: 'A transparent, click-through 3D avatar that floats over your desktop.',
    repo: 'https://github.com/DisplayXR/displayxr-demo-avatar',
  },
  {
    key: 'gaussiansplat',
    name: 'Gaussian Splat Viewer',
    blurb: 'Interactive viewer for 3D Gaussian Splatting scenes (.spz / .ply).',
    repo: 'https://github.com/DisplayXR/displayxr-demo-gaussiansplat',
  },
  {
    key: 'modelviewer',
    name: '3D Model Viewer',
    blurb: 'Interactive PBR viewer for 3D models (.glb / .gltf).',
    repo: 'https://github.com/DisplayXR/displayxr-demo-modelviewer',
  },
  {
    key: 'earthview',
    name: 'EarthView',
    blurb: 'Streaming 3D city viewer on Google Photorealistic 3D Tiles.',
    repo: 'https://github.com/DisplayXR/displayxr-demo-earthview',
  },
];

// Native SBS logo dimensions (1024x512 = two 512x512 eyes).
const SBS_W = 1024;
const SBS_H = 512;
const EYE_W = SBS_W / 2; // 512

// Paint a tile's logo in its current mode. |tile.sbs| true -> full side-by-side
// buffer (the weave input); false -> left (L) half only (flat 2D fallback).
function paintLogo(tile) {
  const { ctx, img } = tile;
  if (!img.complete || img.naturalWidth === 0) {
    return;
  }
  const c = ctx.canvas;
  if (tile.sbs) {
    ctx.drawImage(img, 0, 0, SBS_W, SBS_H, 0, 0, c.width, c.height); // full SBS
  } else {
    ctx.drawImage(img, 0, 0, EYE_W, SBS_H, 0, 0, c.width, c.height); // L eye only
  }
}

// Switch a tile between the 2:1 SBS buffer (woven) and the square left-eye buffer
// (flat). The on-screen box stays square via CSS; only the backing buffer changes.
function setMode(tile, sbs) {
  tile.sbs = sbs;
  tile.canvas.width = sbs ? SBS_W : EYE_W;
  tile.canvas.height = SBS_H;
  paintLogo(tile);
}

function buildTiles() {
  const grid = document.getElementById('grid');
  const tiles = [];
  for (const demo of DEMOS) {
    const card = document.createElement('a');
    card.className = 'tile';
    card.href = demo.repo;
    card.target = '_blank';
    card.rel = 'noopener';

    const stage = document.createElement('div');
    stage.className = 'stage';
    const canvas = document.createElement('canvas');
    canvas.className = 'logo';
    // Own compositing layer so the element is a distinct target for the weave.
    canvas.style.willChange = 'transform';
    canvas.style.transform = 'translateZ(0)';
    stage.appendChild(canvas);

    const meta = document.createElement('div');
    meta.className = 'meta';
    meta.innerHTML =
      `<h2>${demo.name}</h2><p>${demo.blurb}</p>` +
      `<span class="repo">${demo.repo.replace('https://github.com/', '')} ↗</span>`;

    card.appendChild(stage);
    card.appendChild(meta);
    grid.appendChild(card);

    const img = new Image();
    img.src = `assets/${demo.key}.png`;
    const tile = { demo, canvas, ctx: canvas.getContext('2d', { alpha: false }), img, sbs: false };
    setMode(tile, false); // default to a valid flat buffer until the mode resolves
    img.onload = () => paintLogo(tile);
    tiles.push(tile);
  }
  return tiles;
}

function setStatus(mode, detail) {
  const el = document.getElementById('status');
  el.className = 'status ' + mode;
  el.textContent = detail;
}

(async function main() {
  const tiles = buildTiles();

  // Detect the DisplayXR Browser by actually opening an inline-3D session. Unlike
  // isSessionSupported() (an async round-trip to the browser weave client, which
  // may not be bound yet at page load -> a false negative), requestSession is
  // Blink-local and resolves immediately when the feature is present. On an
  // ordinary browser navigator.xr is absent or the unknown mode rejects -> flat.
  let session = null;
  if (navigator.xr) {
    try {
      session = await navigator.xr.requestSession('inline-3d');
    } catch (e) {
      session = null;
    }
  }

  if (!session) {
    setStatus('flat',
      'Flat 2D preview — open in the DisplayXR Browser on a 3D display to see the logos woven in glasses-free 3D.');
    return; // tiles already painted flat (left eye)
  }

  // DisplayXR Browser: switch every tile to its SBS buffer and weave.
  tiles.forEach((t) => setMode(t, true));
  setStatus('woven', 'DisplayXR Browser detected — weaving ' + tiles.length + ' 3D logos inline.');

  // A reference space is required before requestAnimationFrame will fire.
  await session.requestReferenceSpace('viewer').catch(() => null);

  // One XRDisplayLayer per canvas. The session tracks the whole set and reports
  // every canvas rect to the compositor each XR frame (multi-element weave).
  const layers = tiles.map((t) => new XRDisplayLayer(session, t.canvas, {}));
  window.__gallery = { session, layers, tiles, xrFrames: 0 };

  // Repaint the (static) SBS logos every frame so each canvas layer stays live and
  // keeps producing a composited quad for the weave to read.
  function paintFrame() {
    tiles.forEach(paintLogo);
    requestAnimationFrame(paintFrame);
  }
  requestAnimationFrame(paintFrame);

  // Drive the XR session frame loop: this is what makes XRSession report the set
  // of inline-3d rects to Viz each frame (rects=N). Without it no rect reaches
  // the compositor and nothing weaves.
  function onXRFrame(t, frame) {
    window.__gallery.xrFrames++;
    session.requestAnimationFrame(onXRFrame);
  }
  session.requestAnimationFrame(onXRFrame);
})();
